export enum PurchaseOrderStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  SENT_TO_VENDOR = 'SENT_TO_VENDOR',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  PARTIALLY_DELIVERED = 'PARTIALLY_DELIVERED',
  FULLY_DELIVERED = 'FULLY_DELIVERED',
  CANCELLED = 'CANCELLED',
  CLOSED = 'CLOSED',
}

export enum PurchaseOrderApprovalStatus {
  NOT_STARTED = 'NOT_STARTED',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SEND_BACK = 'SEND_BACK',
}

export enum PurchaseOrderChargeType {
  DELIVERY = 'DELIVERY',
  INSTALLATION = 'INSTALLATION',
  TRANSPORTATION = 'TRANSPORTATION',
  LOADING = 'LOADING',
  UNLOADING = 'UNLOADING',
  OTHER = 'OTHER',
}

export const PO_RECEIPT_STATUSES = [
  PurchaseOrderStatus.APPROVED,
  PurchaseOrderStatus.SENT_TO_VENDOR,
  PurchaseOrderStatus.ACKNOWLEDGED,
  PurchaseOrderStatus.PARTIALLY_DELIVERED,
];
