export const BusinessModule = {
  USER: 'USER',
  LEAD: 'LEAD',
  OPPORTUNITY: 'OPPORTUNITY',
  TENDER: 'TENDER',
  REQUIREMENT: 'REQUIREMENT',
  QUOTATION: 'QUOTATION',
  PROJECT: 'PROJECT',
  SITE: 'SITE',
  MATERIAL: 'MATERIAL',
  BOQ: 'BOQ',
  MATERIAL_REQUEST: 'MATERIAL_REQUEST',
  RFQ: 'RFQ',
  PURCHASE_ORDER: 'PURCHASE_ORDER',
  GRN: 'GRN',
  INVOICE: 'INVOICE',
  PAYMENT: 'PAYMENT',
  VENDOR: 'VENDOR',
  MATERIAL_CATEGORY: 'MATERIAL_CATEGORY',
  BOQ_ITEM: 'BOQ_ITEM',
  MATERIAL_REQUEST_ITEM: 'MATERIAL_REQUEST_ITEM',
  EMPLOYEE: 'EMPLOYEE',
  SITE_ACCESS_REQUEST: 'SITE_ACCESS_REQUEST',
  PURCHASE_ORDER_ITEM: 'PURCHASE_ORDER_ITEM',
  PURCHASE_ORDER_CHARGE: 'PURCHASE_ORDER_CHARGE',
  DELIVERY: 'DELIVERY',
  DELIVERY_ITEM: 'DELIVERY_ITEM',
  GRN_ITEM: 'GRN_ITEM',
} as const;

export type BusinessModuleCode =
  (typeof BusinessModule)[keyof typeof BusinessModule];

export const WorkflowModule = {
  MATERIAL_APPROVAL: 'MATERIAL_APPROVAL',
  TENDER_APPROVAL: 'TENDER_APPROVAL',
  PURCHASE_APPROVAL: 'PURCHASE_APPROVAL',
  PO_APPROVAL: 'PO_APPROVAL',
  GRN_APPROVAL: 'GRN_APPROVAL',
  INVOICE_APPROVAL: 'INVOICE_APPROVAL',
  SITE_ACCESS: 'SITE_ACCESS',
  BOQ_APPROVAL: 'BOQ_APPROVAL',
  GENERIC: 'GENERIC',
} as const;

export type WorkflowModuleCode =
  (typeof WorkflowModule)[keyof typeof WorkflowModule];

export const DocumentType = {
  LEAD: 'LEAD',
  OPPORTUNITY: 'OPPORTUNITY',
  TENDER: 'TENDER',
  PROJECT: 'PROJECT',
  MATERIAL_REQUEST: 'MATERIAL_REQUEST',
  RFQ: 'RFQ',
  QUOTATION: 'QUOTATION',
  PURCHASE_ORDER: 'PURCHASE_ORDER',
  PO: 'PO',
  DELIVERY: 'DELIVERY',
  GRN: 'GRN',
  INVOICE: 'INVOICE',
  PAYMENT: 'PAYMENT',
  BOQ: 'BOQ',
  EMPLOYEE: 'EMPLOYEE',
  MR: 'MR',
} as const;

export type DocumentTypeCode = (typeof DocumentType)[keyof typeof DocumentType];
