export const PermissionCode = {
  TENANTS_CREATE: 'tenants.create',
  TENANTS_READ: 'tenants.read',
  TENANTS_UPDATE: 'tenants.update',
  TENANTS_DELETE: 'tenants.delete',
  USERS_CREATE: 'users.create',
  USERS_READ: 'users.read',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  ROLES_CREATE: 'roles.create',
  ROLES_READ: 'roles.read',
  ROLES_UPDATE: 'roles.update',
  ROLES_DELETE: 'roles.delete',
  PERMISSIONS_READ: 'permissions.read',
  CUSTOM_FIELDS_CREATE: 'custom-fields.create',
  CUSTOM_FIELDS_READ: 'custom-fields.read',
  CUSTOM_FIELDS_UPDATE: 'custom-fields.update',
  CUSTOM_FIELDS_DELETE: 'custom-fields.delete',
  WORKFLOW_CREATE: 'workflow.create',
  WORKFLOW_READ: 'workflow.read',
  WORKFLOW_UPDATE: 'workflow.update',
  WORKFLOW_ACT: 'workflow.act',
  SLA_READ: 'sla.read',
  SLA_UPDATE: 'sla.update',
  NOTIFICATIONS_READ: 'notifications.read',
  NOTIFICATIONS_UPDATE: 'notifications.update',
  AUDIT_READ: 'audit.read',
  NUMBERING_READ: 'numbering.read',
  NUMBERING_CREATE: 'numbering.create',
  LEADS_CREATE: 'leads.create',
  LEADS_READ: 'leads.read',
  LEADS_UPDATE: 'leads.update',
  LEADS_DELETE: 'leads.delete',
  OPPORTUNITIES_CREATE: 'opportunities.create',
  OPPORTUNITIES_READ: 'opportunities.read',
  OPPORTUNITIES_UPDATE: 'opportunities.update',
  TENDERS_CREATE: 'tenders.create',
  TENDERS_READ: 'tenders.read',
  TENDERS_UPDATE: 'tenders.update',
  REQUIREMENTS_CREATE: 'requirements.create',
  REQUIREMENTS_READ: 'requirements.read',
  REQUIREMENTS_UPDATE: 'requirements.update',
  QUOTATIONS_CREATE: 'quotations.create',
  QUOTATIONS_READ: 'quotations.read',
  QUOTATIONS_UPDATE: 'quotations.update',
  CLIENT_DECISIONS_CREATE: 'client-decisions.create',
  CLIENT_DECISIONS_READ: 'client-decisions.read',
  PROJECTS_CREATE: 'projects.create',
  PROJECTS_READ: 'projects.read',
  PROJECTS_UPDATE: 'projects.update',
  SITES_CREATE: 'sites.create',
  SITES_READ: 'sites.read',
  SITES_UPDATE: 'sites.update',
  MATERIALS_CREATE: 'materials.create',
  MATERIALS_READ: 'materials.read',
  MATERIALS_UPDATE: 'materials.update',
  CATEGORIES_CREATE: 'material-categories.create',
  CATEGORIES_READ: 'material-categories.read',
  CATEGORIES_UPDATE: 'material-categories.update',
  CATEGORIES_DELETE: 'material-categories.delete',
  UNITS_CREATE: 'units.create',
  UNITS_READ: 'units.read',
  UNITS_UPDATE: 'units.update',
  UNITS_DELETE: 'units.delete',
  BOQ_CREATE: 'boq.create',
  BOQ_READ: 'boq.read',
  BOQ_UPDATE: 'boq.update',
  PLANNING_CREATE: 'material-planning.create',
  PLANNING_READ: 'material-planning.read',
  PLANNING_UPDATE: 'material-planning.update',
  MR_CREATE: 'material-requests.create',
  MR_READ: 'material-requests.read',
  MR_UPDATE: 'material-requests.update',
  EMPLOYEES_CREATE: 'employees.create',
  EMPLOYEES_READ: 'employees.read',
  EMPLOYEES_UPDATE: 'employees.update',
  ASSIGNMENTS_CREATE: 'site-assignments.create',
  ASSIGNMENTS_READ: 'site-assignments.read',
  ASSIGNMENTS_UPDATE: 'site-assignments.update',
  ATTENDANCE_READ: 'attendance.read',
  ATTENDANCE_PUNCH: 'attendance.punch',
  SITE_ACCESS_CREATE: 'site-access.create',
  SITE_ACCESS_READ: 'site-access.read',
  SITE_ACCESS_UPDATE: 'site-access.update',
  PO_CREATE: 'purchase-orders.create',
  PO_READ: 'purchase-orders.read',
  PO_UPDATE: 'purchase-orders.update',
  DELIVERY_CREATE: 'deliveries.create',
  DELIVERY_READ: 'deliveries.read',
  DELIVERY_UPDATE: 'deliveries.update',
  GRN_CREATE: 'grns.create',
  GRN_READ: 'grns.read',
  GRN_UPDATE: 'grns.update',
  INVOICES_CREATE: 'invoices.create',
  INVOICES_READ: 'invoices.read',
  INVOICES_UPDATE: 'invoices.update',
  INVOICES_SUBMIT: 'invoices.submit',
  INVOICES_MATCH: 'invoices.match',
  INVOICES_REVIEW: 'invoices.review',
  INVOICES_HOLD: 'invoices.hold',
  INVOICES_APPROVE: 'invoices.approve',
  INVOICES_REJECT: 'invoices.reject',
  INVOICES_CANCEL: 'invoices.cancel',
} as const;

export type PermissionCodeValue =
  (typeof PermissionCode)[keyof typeof PermissionCode];

export const ALL_PERMISSIONS: PermissionCodeValue[] =
  Object.values(PermissionCode);

export const TENANT_ADMIN_PERMISSIONS: PermissionCodeValue[] = [
  PermissionCode.USERS_CREATE,
  PermissionCode.USERS_READ,
  PermissionCode.USERS_UPDATE,
  PermissionCode.USERS_DELETE,
  PermissionCode.ROLES_CREATE,
  PermissionCode.ROLES_READ,
  PermissionCode.ROLES_UPDATE,
  PermissionCode.ROLES_DELETE,
  PermissionCode.PERMISSIONS_READ,
  PermissionCode.CUSTOM_FIELDS_CREATE,
  PermissionCode.CUSTOM_FIELDS_READ,
  PermissionCode.CUSTOM_FIELDS_UPDATE,
  PermissionCode.CUSTOM_FIELDS_DELETE,
  PermissionCode.WORKFLOW_CREATE,
  PermissionCode.WORKFLOW_READ,
  PermissionCode.WORKFLOW_UPDATE,
  PermissionCode.WORKFLOW_ACT,
  PermissionCode.SLA_READ,
  PermissionCode.SLA_UPDATE,
  PermissionCode.NOTIFICATIONS_READ,
  PermissionCode.NOTIFICATIONS_UPDATE,
  PermissionCode.AUDIT_READ,
  PermissionCode.NUMBERING_READ,
  PermissionCode.NUMBERING_CREATE,
  PermissionCode.LEADS_CREATE,
  PermissionCode.LEADS_READ,
  PermissionCode.LEADS_UPDATE,
  PermissionCode.LEADS_DELETE,
  PermissionCode.OPPORTUNITIES_CREATE,
  PermissionCode.OPPORTUNITIES_READ,
  PermissionCode.OPPORTUNITIES_UPDATE,
  PermissionCode.TENDERS_CREATE,
  PermissionCode.TENDERS_READ,
  PermissionCode.TENDERS_UPDATE,
  PermissionCode.REQUIREMENTS_CREATE,
  PermissionCode.REQUIREMENTS_READ,
  PermissionCode.REQUIREMENTS_UPDATE,
  PermissionCode.QUOTATIONS_CREATE,
  PermissionCode.QUOTATIONS_READ,
  PermissionCode.QUOTATIONS_UPDATE,
  PermissionCode.CLIENT_DECISIONS_CREATE,
  PermissionCode.CLIENT_DECISIONS_READ,
  PermissionCode.PROJECTS_CREATE,
  PermissionCode.PROJECTS_READ,
  PermissionCode.PROJECTS_UPDATE,
  PermissionCode.SITES_CREATE,
  PermissionCode.SITES_READ,
  PermissionCode.SITES_UPDATE,
  PermissionCode.MATERIALS_CREATE,
  PermissionCode.MATERIALS_READ,
  PermissionCode.MATERIALS_UPDATE,
  PermissionCode.CATEGORIES_CREATE,
  PermissionCode.CATEGORIES_READ,
  PermissionCode.CATEGORIES_UPDATE,
  PermissionCode.CATEGORIES_DELETE,
  PermissionCode.UNITS_CREATE,
  PermissionCode.UNITS_READ,
  PermissionCode.UNITS_UPDATE,
  PermissionCode.UNITS_DELETE,
  PermissionCode.BOQ_CREATE,
  PermissionCode.BOQ_READ,
  PermissionCode.BOQ_UPDATE,
  PermissionCode.PLANNING_CREATE,
  PermissionCode.PLANNING_READ,
  PermissionCode.PLANNING_UPDATE,
  PermissionCode.MR_CREATE,
  PermissionCode.MR_READ,
  PermissionCode.MR_UPDATE,
  PermissionCode.EMPLOYEES_CREATE,
  PermissionCode.EMPLOYEES_READ,
  PermissionCode.EMPLOYEES_UPDATE,
  PermissionCode.ASSIGNMENTS_CREATE,
  PermissionCode.ASSIGNMENTS_READ,
  PermissionCode.ASSIGNMENTS_UPDATE,
  PermissionCode.ATTENDANCE_READ,
  PermissionCode.ATTENDANCE_PUNCH,
  PermissionCode.SITE_ACCESS_CREATE,
  PermissionCode.SITE_ACCESS_READ,
  PermissionCode.SITE_ACCESS_UPDATE,
  PermissionCode.PO_CREATE,
  PermissionCode.PO_READ,
  PermissionCode.PO_UPDATE,
  PermissionCode.DELIVERY_CREATE,
  PermissionCode.DELIVERY_READ,
  PermissionCode.DELIVERY_UPDATE,
  PermissionCode.GRN_CREATE,
  PermissionCode.GRN_READ,
  PermissionCode.GRN_UPDATE,
  PermissionCode.INVOICES_CREATE,
  PermissionCode.INVOICES_READ,
  PermissionCode.INVOICES_UPDATE,
  PermissionCode.INVOICES_SUBMIT,
  PermissionCode.INVOICES_MATCH,
  PermissionCode.INVOICES_REVIEW,
  PermissionCode.INVOICES_HOLD,
  PermissionCode.INVOICES_APPROVE,
  PermissionCode.INVOICES_REJECT,
  PermissionCode.INVOICES_CANCEL,
];

export const DEFAULT_ROLE_PERMISSIONS: Record<string, PermissionCodeValue[]> = {
  TENANT_ADMIN: TENANT_ADMIN_PERMISSIONS,
  MD: [
    PermissionCode.USERS_READ,
    PermissionCode.ROLES_READ,
    PermissionCode.WORKFLOW_READ,
    PermissionCode.WORKFLOW_ACT,
    PermissionCode.NOTIFICATIONS_READ,
    PermissionCode.AUDIT_READ,
    PermissionCode.LEADS_READ,
    PermissionCode.OPPORTUNITIES_READ,
    PermissionCode.TENDERS_READ,
    PermissionCode.QUOTATIONS_READ,
    PermissionCode.PROJECTS_READ,
    PermissionCode.SITES_READ,
    PermissionCode.MATERIALS_READ,
    PermissionCode.BOQ_READ,
    PermissionCode.MR_READ,
    PermissionCode.ATTENDANCE_READ,
    PermissionCode.PO_READ,
    PermissionCode.DELIVERY_READ,
    PermissionCode.GRN_READ,
    PermissionCode.INVOICES_READ,
  ],
  DIRECTOR: [
    PermissionCode.USERS_READ,
    PermissionCode.ROLES_READ,
    PermissionCode.WORKFLOW_READ,
    PermissionCode.WORKFLOW_ACT,
    PermissionCode.NOTIFICATIONS_READ,
    PermissionCode.LEADS_READ,
    PermissionCode.OPPORTUNITIES_READ,
    PermissionCode.TENDERS_READ,
    PermissionCode.PROJECTS_READ,
    PermissionCode.MATERIALS_READ,
    PermissionCode.BOQ_READ,
    PermissionCode.MR_READ,
    PermissionCode.PO_READ,
    PermissionCode.GRN_READ,
    PermissionCode.INVOICES_READ,
  ],
  PROJECT_HEAD: [
    PermissionCode.USERS_READ,
    PermissionCode.WORKFLOW_READ,
    PermissionCode.WORKFLOW_ACT,
    PermissionCode.NOTIFICATIONS_READ,
    PermissionCode.LEADS_READ,
    PermissionCode.LEADS_UPDATE,
    PermissionCode.OPPORTUNITIES_READ,
    PermissionCode.OPPORTUNITIES_UPDATE,
    PermissionCode.TENDERS_READ,
    PermissionCode.TENDERS_UPDATE,
    PermissionCode.REQUIREMENTS_READ,
    PermissionCode.QUOTATIONS_READ,
    PermissionCode.PROJECTS_READ,
    PermissionCode.PROJECTS_UPDATE,
    PermissionCode.SITES_READ,
    PermissionCode.SITES_UPDATE,
    PermissionCode.MATERIALS_READ,
    PermissionCode.CATEGORIES_READ,
    PermissionCode.UNITS_READ,
    PermissionCode.BOQ_CREATE,
    PermissionCode.BOQ_READ,
    PermissionCode.BOQ_UPDATE,
    PermissionCode.PLANNING_CREATE,
    PermissionCode.PLANNING_READ,
    PermissionCode.PLANNING_UPDATE,
    PermissionCode.MR_CREATE,
    PermissionCode.MR_READ,
    PermissionCode.MR_UPDATE,
    PermissionCode.EMPLOYEES_READ,
    PermissionCode.ASSIGNMENTS_READ,
    PermissionCode.ATTENDANCE_READ,
    PermissionCode.PO_READ,
    PermissionCode.PO_UPDATE,
    PermissionCode.DELIVERY_READ,
    PermissionCode.GRN_READ,
    PermissionCode.GRN_UPDATE,
    PermissionCode.INVOICES_READ,
  ],
  SITE_ENGINEER: [
    PermissionCode.USERS_READ,
    PermissionCode.WORKFLOW_READ,
    PermissionCode.NOTIFICATIONS_READ,
    PermissionCode.MR_CREATE,
    PermissionCode.MR_READ,
    PermissionCode.ASSIGNMENTS_READ,
    PermissionCode.ATTENDANCE_PUNCH,
    PermissionCode.ATTENDANCE_READ,
    PermissionCode.SITE_ACCESS_CREATE,
    PermissionCode.SITE_ACCESS_READ,
    PermissionCode.PO_READ,
    PermissionCode.DELIVERY_CREATE,
    PermissionCode.DELIVERY_READ,
    PermissionCode.DELIVERY_UPDATE,
    PermissionCode.GRN_CREATE,
    PermissionCode.GRN_READ,
    PermissionCode.GRN_UPDATE,
    PermissionCode.INVOICES_CREATE,
    PermissionCode.INVOICES_READ,
    PermissionCode.INVOICES_UPDATE,
    PermissionCode.INVOICES_SUBMIT,
    PermissionCode.INVOICES_CANCEL,
  ],
  SITE_MANAGER: [
    PermissionCode.USERS_READ,
    PermissionCode.WORKFLOW_READ,
    PermissionCode.WORKFLOW_ACT,
    PermissionCode.NOTIFICATIONS_READ,
    PermissionCode.MR_READ,
    PermissionCode.ATTENDANCE_READ,
    PermissionCode.SITES_READ,
    PermissionCode.PO_READ,
    PermissionCode.DELIVERY_READ,
    PermissionCode.GRN_READ,
    PermissionCode.INVOICES_READ,
  ],
  HR: [
    PermissionCode.USERS_CREATE,
    PermissionCode.USERS_READ,
    PermissionCode.USERS_UPDATE,
    PermissionCode.WORKFLOW_READ,
    PermissionCode.WORKFLOW_ACT,
    PermissionCode.NOTIFICATIONS_READ,
    PermissionCode.EMPLOYEES_CREATE,
    PermissionCode.EMPLOYEES_READ,
    PermissionCode.EMPLOYEES_UPDATE,
    PermissionCode.ASSIGNMENTS_CREATE,
    PermissionCode.ASSIGNMENTS_READ,
    PermissionCode.ASSIGNMENTS_UPDATE,
    PermissionCode.SITE_ACCESS_READ,
    PermissionCode.SITE_ACCESS_UPDATE,
    PermissionCode.ATTENDANCE_READ,
  ],
  PROCUREMENT: [
    PermissionCode.USERS_READ,
    PermissionCode.WORKFLOW_READ,
    PermissionCode.WORKFLOW_ACT,
    PermissionCode.NOTIFICATIONS_READ,
    PermissionCode.PO_CREATE,
    PermissionCode.PO_READ,
    PermissionCode.PO_UPDATE,
    PermissionCode.DELIVERY_CREATE,
    PermissionCode.DELIVERY_READ,
    PermissionCode.DELIVERY_UPDATE,
    PermissionCode.GRN_CREATE,
    PermissionCode.GRN_READ,
    PermissionCode.GRN_UPDATE,
    PermissionCode.INVOICES_READ,
  ],
  PURCHASE: [
    PermissionCode.USERS_READ,
    PermissionCode.WORKFLOW_READ,
    PermissionCode.WORKFLOW_ACT,
    PermissionCode.NOTIFICATIONS_READ,
    PermissionCode.PO_CREATE,
    PermissionCode.PO_READ,
    PermissionCode.PO_UPDATE,
    PermissionCode.DELIVERY_CREATE,
    PermissionCode.DELIVERY_READ,
    PermissionCode.DELIVERY_UPDATE,
    PermissionCode.GRN_READ,
    PermissionCode.INVOICES_READ,
  ],
  SCM: [
    PermissionCode.USERS_READ,
    PermissionCode.WORKFLOW_READ,
    PermissionCode.NOTIFICATIONS_READ,
    PermissionCode.PO_READ,
    PermissionCode.DELIVERY_READ,
    PermissionCode.GRN_READ,
    PermissionCode.INVOICES_READ,
  ],
  ACCOUNTS: [
    PermissionCode.USERS_READ,
    PermissionCode.WORKFLOW_READ,
    PermissionCode.WORKFLOW_ACT,
    PermissionCode.NOTIFICATIONS_READ,
    PermissionCode.INVOICES_READ,
    PermissionCode.INVOICES_UPDATE,
    PermissionCode.INVOICES_REVIEW,
    PermissionCode.INVOICES_MATCH,
    PermissionCode.INVOICES_HOLD,
    PermissionCode.INVOICES_APPROVE,
    PermissionCode.INVOICES_REJECT,
    PermissionCode.INVOICES_CANCEL,
  ],
  FINANCE: [
    PermissionCode.USERS_READ,
    PermissionCode.WORKFLOW_READ,
    PermissionCode.WORKFLOW_ACT,
    PermissionCode.NOTIFICATIONS_READ,
    PermissionCode.INVOICES_READ,
    PermissionCode.INVOICES_REVIEW,
    PermissionCode.INVOICES_MATCH,
  ],
  EMPLOYEE: [
    PermissionCode.USERS_READ,
    PermissionCode.NOTIFICATIONS_READ,
    PermissionCode.ATTENDANCE_PUNCH,
    PermissionCode.ATTENDANCE_READ,
    PermissionCode.ASSIGNMENTS_READ,
    PermissionCode.SITE_ACCESS_CREATE,
    PermissionCode.SITE_ACCESS_READ,
    PermissionCode.SITES_READ,
  ],
  VENDOR_USER: [],
};
